freebsd_instance:
  image: freebsd-12-1-release-amd64
test_task:
  provision_script:
    - mkdir -p /usr/local/etc/pkg/repos/
    - sed "s#quarterly#latest#" /etc/pkg/FreeBSD.conf > /usr/local/etc/pkg/repos/FreeBSD.conf
    - pkg update -f
    - pkg upgrade -y
    - pkg install -y node12 npm-node12
    - npm i -g @babel/core@7.11 @babel/cli@7.10
  prepare_script: make NPM=/usr/local/bin/npm prepare
  script: npm test
build_task:
  provision_script:
    - mkdir -p /usr/local/etc/pkg/repos/
    - sed "s#quarterly#latest#" /etc/pkg/FreeBSD.conf > /usr/local/etc/pkg/repos/FreeBSD.conf
    - pkg update -f
    - pkg upgrade -y
    - pkg install -y node12 npm-node12
    - npm i -g @babel/core@7.11 @babel/cli@7.10
  depends_on:
    - test
  script:
    - make NPM=/usr/local/bin/npm BABEL=/usr/local/bin/babel
    - make TAR=/usr/bin/tar dist
